# Site settings
title: MMA Fight Picks
name: Fight Picks
subtitle: Analysis, Statistics and Picks
email: aerin00  @gmail.com
description: >
  An MMA analysis and prediction engine and blog
baseurl: ""
url: "https://fightpicks.github.io/"
github_username:  fightpicks
permalink: :title
cover: "/assets/header_image.jpg"
logo: "/assets/nr-logo.jpg"
#ga_tracking_id: "UA-82647777-1"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Nikhita Raghunath"


# External gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

exclude:
  - "/vendor/"

# Collections
collections:
  - talks